### ISSUE TITLE
Not working with tiddlywiki 5.3.6

### ISSUE THREAD

**Issue by malibu1966** [ThaddeusJiang/Projectify#13]
Hi there,  first of all, thank you for making such an awesome plugin for Tiddlywiki.  Tiddlywiki is pretty obscure.. I became aware of it around 15 years ago.  Fast forward to today, I was looking for a way to manage my time that would work offline and be consistent on any system... So I'm back to Tiddlywiki!

I am using TW version 5.3.6 and I have tried dragging the projectify link onto both TiddlyDesktop and the wiki running in Firefox.  Both just open a new tiddly with the link inside and the plugin doesn't seem to install.  Not sure if I am doing anything wrong.  Thanks.

**Comment by ThaddeusJiang** [comment]
I will test it in tiddlywiki 5.3.6

**Comment by chept** [comment]
I'm running Projectify in 5.3.6 on tiddlyhost since 3 days. For now I have no issues.

@malibu1966, drad'n'drop doesn't always works as expected, to be sure you can download the plugin and import as a file:

1. Go to plugin tiddler: https://thaddeusjiang.github.io/Projectify/demo.html#%24%3A%2Fplugins%2Fnico%2Fprojectify
2. Click `More actions` (arrow down button) / `export tiddler` / choose `".tid" file`
3. Save the file then in your wiki click `Import` (paperclip button, found in `Tools` sidebar) and import the .tid file

**Comment by malibu1966** [comment]
This seems to have worked, thank you.
